from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    app_name: str = "OnCall Agent Python"
    app_env: str = "local"
    app_version: str = "0.1.0"
    api_prefix: str = "/api"
    log_level: str = "INFO"
    log_format: str = "json"
    log_file_path: str | None = None
    log_file_max_bytes: int = 10_485_760
    log_file_backup_count: int = 5
    telemetry_service_name: str = "oncall-agent"
    metrics_enabled: bool = True
    metrics_auth_token: str | None = None
    audit_enabled: bool = True
    audit_persist_enabled: bool = True
    audit_retention_days: int = 180
    audit_cleanup_interval_seconds: int = 86400
    api_auth_enabled: bool = False
    api_token: str | None = None
    api_token_subject: str = "api-client"
    api_token_roles: str = "oncall,sre"
    auth_mode: str = "api-token"
    default_tenant_id: str = "default"
    jwt_issuer: str | None = None
    jwt_audience: str | None = None
    jwt_jwks_url: str | None = None
    jwt_secret: str | None = None
    jwt_algorithms: str = "RS256"
    jwt_tenant_claim: str = "tenant_id"
    jwt_roles_claim: str = "roles"
    jwt_permissions_claim: str = "permissions"
    jwt_clock_skew_seconds: int = 30
    webhook_secret: str | None = None
    alertmanager_webhook_token: str | None = None
    require_auth_in_production: bool = True
    database_url: str | None = None
    database_pool_size: int = 10
    database_max_overflow: int = 20
    database_pool_timeout_seconds: int = 30
    database_pool_recycle_seconds: int = 1800
    database_auto_create_schema: bool = True
    task_queue_mode: str = "local"
    redis_url: str = "redis://localhost:6380/0"
    celery_result_backend: str | None = None
    celery_task_always_eager: bool = False
    celery_task_eager_propagates: bool = True
    celery_result_expires_seconds: int = 3600
    task_dispatch_dedupe_ttl_seconds: int = 30
    task_execution_lock_ttl_seconds: int = 3600
    task_broker_publish_max_retries: int = 3
    task_broker_publish_retry_delay_seconds: float = 0.2
    stale_task_recovery_interval_seconds: int = 60
    stale_task_auto_resume_enabled: bool = True
    redis_key_prefix: str = "oncall-agent"
    llm_provider: str = "mock"
    llm_model: str = "mock-oncall-agent"
    llm_api_key: str | None = None
    llm_base_url: str = "https://api.openai.com/v1"
    llm_timeout_seconds: int = 30
    llm_max_retries: int = 6
    embedding_provider: str = "hash"
    embedding_model: str = "text-embedding-3-small"
    embedding_api_key: str | None = None
    embedding_base_url: str = "https://api.openai.com/v1"
    embedding_dimensions: int = 1536
    embedding_request_dimensions: bool = False
    embedding_tiktoken_enabled: bool = False
    embedding_check_ctx_length: bool = False
    embedding_timeout_seconds: int = 30
    embedding_max_retries: int = 6
    knowledge_vector_store: str = "in_memory"
    knowledge_source: str = "local"
    knowledge_local_path: str = "app/data/runbooks"
    knowledge_github_path: str = "app/data/runbooks"
    knowledge_ingest_chunk_size: int = 800
    knowledge_ingest_chunk_overlap: int = 120
    knowledge_allowed_extensions: str = ".md,.txt,.pdf,.docx"
    knowledge_default_access_scope: str = "internal"
    knowledge_default_allowed_roles: str = "oncall,sre"
    knowledge_acl_enabled: bool = True
    knowledge_system_subject: str = "oncall-agent"
    knowledge_system_roles: str = "oncall,sre"
    knowledge_incremental_indexing_enabled: bool = True
    knowledge_manifest_db_path: str = "app/data/knowledge_manifest.db"
    knowledge_ingestion_task_db_path: str = "app/data/knowledge_ingestion_tasks.db"
    knowledge_ingestion_max_attempts: int = 3
    workflow_db_path: str = "app/data/workflows.db"
    workflow_checkpointer: str = "sqlite"
    workflow_checkpoint_db_path: str = "app/data/workflow_langgraph_checkpoints.sqlite"
    milvus_uri: str | None = None
    milvus_token: str | None = None
    milvus_db_name: str | None = None
    milvus_collection_name: str = "oncall_runbook_chunks"
    milvus_vector_field: str = "vector"
    milvus_primary_field: str = "chunk_id"
    milvus_metric_type: str = "COSINE"
    incident_db_path: str = "app/data/oncall_agent.db"
    ops_tool_mode: str = "mock"
    prometheus_base_url: str | None = None
    prometheus_timeout_seconds: int = 10
    prometheus_bearer_token: str | None = None
    prometheus_username: str | None = None
    prometheus_password: str | None = None
    prometheus_verify_ssl: bool = True
    loki_base_url: str | None = None
    loki_timeout_seconds: int = 10
    loki_bearer_token: str | None = None
    loki_username: str | None = None
    loki_password: str | None = None
    loki_org_id: str | None = None
    loki_verify_ssl: bool = True
    gitlab_base_url: str | None = None
    gitlab_token: str | None = None
    gitlab_project_id: str | None = None
    gitlab_timeout_seconds: int = 10
    github_token: str | None = None
    github_base_url: str = "https://api.github.com"
    github_repo: str | None = None
    github_branch: str = "main"
    github_timeout_seconds: int = 10
    github_verify_ssl: bool = True
    github_proxy_url: str | None = None
    github_allowed_paths: str = ""
    github_max_file_bytes: int = 2_000_000
    github_max_patch_chars: int = 4000
    payment_api_remediation_enabled: bool = False
    payment_api_base_url: str | None = None
    payment_api_fault_admin_token: str | None = None
    payment_api_timeout_seconds: int = 10
    payment_api_verify_ssl: bool = True
    ops_http_max_connections: int = 20
    ops_http_max_keepalive_connections: int = 10
    knowledge_engine: str = "local"
    knowledge_reranker: str = "llamaindex"
    knowledge_rerank_candidate_multiplier: int = 3
    knowledge_rerank_vector_weight: float = 0.7
    knowledge_rerank_lexical_weight: float = 0.3
    tool_retry_max_attempts: int = 3
    tool_retry_base_delay_seconds: float = 0.05
    tool_retry_max_delay_seconds: float = 1.0
    diagnosis_task_timeout_seconds: int = 900
    diagnosis_task_recovery_limit: int = 50
    ops_graph_runtime: str = "local"
    ops_graph_checkpointer: str = "memory"
    ops_graph_checkpoint_db_path: str = "app/data/langgraph_checkpoints.sqlite"
    knowledge_retriever_mode: str = "keyword"

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )


settings = Settings()
