"""create enterprise persistence schema

Revision ID: ad29048b8972
Revises: 
Create Date: 2026-07-23 19:49:48.735692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad29048b8972'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_groups',
    sa.Column('group_id', sa.Text(), nullable=False),
    sa.Column('dedupe_key', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('service', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('labels_json', sa.Text(), nullable=False),
    sa.Column('annotations_json', sa.Text(), nullable=False),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('latest_task_id', sa.Text(), nullable=True),
    sa.Column('incident_id', sa.Text(), nullable=True),
    sa.Column('diagnosis_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.Text(), nullable=False),
    sa.Column('last_seen_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_alert_groups')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_alert_groups_dedupe_key'))
    )
    with op.batch_alter_table('alert_groups', schema=None) as batch_op:
        batch_op.create_index('idx_alert_groups_status_last_seen', ['status', sa.literal_column('last_seen_at DESC')], unique=False)

    op.create_table('diagnosis_tasks',
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('alert_group_id', sa.Text(), nullable=True),
    sa.Column('rerun_of_task_id', sa.Text(), nullable=True),
    sa.Column('resume_of_task_id', sa.Text(), nullable=True),
    sa.Column('thread_id', sa.Text(), nullable=True),
    sa.Column('run_id', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('service', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('labels_json', sa.Text(), nullable=False),
    sa.Column('trigger_metadata_json', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('incident_id', sa.Text(), nullable=True),
    sa.Column('diagnosis_id', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_diagnosis_tasks'))
    )
    with op.batch_alter_table('diagnosis_tasks', schema=None) as batch_op:
        batch_op.create_index('idx_diagnosis_tasks_rerun_of', ['rerun_of_task_id', 'created_at'], unique=False)
        batch_op.create_index('idx_diagnosis_tasks_resume_of', ['resume_of_task_id', 'created_at'], unique=False)
        batch_op.create_index('idx_diagnosis_tasks_status_updated', ['status', 'updated_at'], unique=False)
        batch_op.create_index('idx_diagnosis_tasks_thread_created', ['thread_id', 'created_at'], unique=False)

    op.create_table('incidents',
    sa.Column('incident_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('service', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('labels_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('incident_id', name=op.f('pk_incidents'))
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('idx_incidents_service_status_created', ['service', 'status', sa.literal_column('created_at DESC')], unique=False)

    op.create_table('knowledge_index_manifest',
    sa.Column('namespace', sa.Text(), nullable=False),
    sa.Column('doc_id', sa.Text(), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=False),
    sa.Column('source_version', sa.Text(), nullable=False),
    sa.Column('document_signature', sa.Text(), nullable=False),
    sa.Column('index_signature', sa.Text(), nullable=False),
    sa.Column('chunk_ids_json', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('indexed_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('namespace', 'doc_id', name=op.f('pk_knowledge_index_manifest'))
    )
    with op.batch_alter_table('knowledge_index_manifest', schema=None) as batch_op:
        batch_op.create_index('idx_knowledge_manifest_namespace', ['namespace'], unique=False)

    op.create_table('knowledge_ingestion_tasks',
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('request_json', sa.Text(), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('progress_stage', sa.Text(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_knowledge_ingestion_tasks'))
    )
    with op.batch_alter_table('knowledge_ingestion_tasks', schema=None) as batch_op:
        batch_op.create_index('idx_knowledge_ingestion_tasks_status_created', ['status', sa.literal_column('created_at DESC')], unique=False)

    op.create_table('workflow_applications',
    sa.Column('app_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('app_id', name=op.f('pk_workflow_applications'))
    )
    with op.batch_alter_table('workflow_applications', schema=None) as batch_op:
        batch_op.create_index('idx_workflow_applications_status_updated', ['status', sa.literal_column('updated_at DESC')], unique=False)

    op.create_table('diagnoses',
    sa.Column('diagnosis_id', sa.Text(), nullable=False),
    sa.Column('incident_id', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('sources_json', sa.Text(), nullable=False),
    sa.Column('tool_results_json', sa.Text(), nullable=False),
    sa.Column('react_steps_json', sa.Text(), nullable=False),
    sa.Column('plan_trace_json', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], name=op.f('fk_diagnoses_incident_id_incidents')),
    sa.PrimaryKeyConstraint('diagnosis_id', name=op.f('pk_diagnoses'))
    )
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.create_index('idx_diagnoses_incident_created', ['incident_id', sa.literal_column('created_at DESC')], unique=False)

    op.create_table('diagnosis_task_events',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['diagnosis_tasks.task_id'], name=op.f('fk_diagnosis_task_events_task_id_diagnosis_tasks')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_diagnosis_task_events'))
    )
    with op.batch_alter_table('diagnosis_task_events', schema=None) as batch_op:
        batch_op.create_index('idx_diagnosis_task_events_task_created', ['task_id', 'created_at'], unique=False)

    op.create_table('human_review_requests',
    sa.Column('review_id', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('service', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('proposed_actions_json', sa.Text(), nullable=False),
    sa.Column('risk_reasons_json', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('reviewer', sa.Text(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['diagnosis_tasks.task_id'], name=op.f('fk_human_review_requests_task_id_diagnosis_tasks')),
    sa.PrimaryKeyConstraint('review_id', name=op.f('pk_human_review_requests'))
    )
    with op.batch_alter_table('human_review_requests', schema=None) as batch_op:
        batch_op.create_index('idx_human_review_requests_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('idx_human_review_requests_task_created', ['task_id', 'created_at'], unique=False)

    op.create_table('knowledge_ingestion_attempts',
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('progress_stage', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.Text(), nullable=False),
    sa.Column('finished_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['knowledge_ingestion_tasks.task_id'], name=op.f('fk_knowledge_ingestion_attempts_task_id_knowledge_ingestion_tasks')),
    sa.PrimaryKeyConstraint('task_id', 'attempt', name=op.f('pk_knowledge_ingestion_attempts'))
    )
    with op.batch_alter_table('knowledge_ingestion_attempts', schema=None) as batch_op:
        batch_op.create_index('idx_knowledge_ingestion_attempts_status', ['status', sa.literal_column('started_at DESC')], unique=False)

    op.create_table('ops_graph_checkpoints',
    sa.Column('checkpoint_id', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('thread_id', sa.Text(), nullable=True),
    sa.Column('run_id', sa.Text(), nullable=True),
    sa.Column('node_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('state_json', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['diagnosis_tasks.task_id'], name=op.f('fk_ops_graph_checkpoints_task_id_diagnosis_tasks')),
    sa.PrimaryKeyConstraint('checkpoint_id', name=op.f('pk_ops_graph_checkpoints'))
    )
    with op.batch_alter_table('ops_graph_checkpoints', schema=None) as batch_op:
        batch_op.create_index('idx_ops_graph_checkpoints_task_created', ['task_id', 'created_at'], unique=False)
        batch_op.create_index('idx_ops_graph_checkpoints_thread_run', ['thread_id', 'run_id', 'created_at'], unique=False)

    op.create_table('workflow_audit_events',
    sa.Column('audit_id', sa.Text(), nullable=False),
    sa.Column('app_id', sa.Text(), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Text(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['workflow_applications.app_id'], name=op.f('fk_workflow_audit_events_app_id_workflow_applications')),
    sa.PrimaryKeyConstraint('audit_id', name=op.f('pk_workflow_audit_events'))
    )
    with op.batch_alter_table('workflow_audit_events', schema=None) as batch_op:
        batch_op.create_index('idx_workflow_audit_app_created', ['app_id', sa.literal_column('created_at DESC')], unique=False)

    op.create_table('workflow_drafts',
    sa.Column('draft_id', sa.Text(), nullable=False),
    sa.Column('app_id', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('graph_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['workflow_applications.app_id'], name=op.f('fk_workflow_drafts_app_id_workflow_applications')),
    sa.PrimaryKeyConstraint('draft_id', name=op.f('pk_workflow_drafts')),
    sa.UniqueConstraint('app_id', name=op.f('uq_workflow_drafts_app_id'))
    )
    op.create_table('workflow_runs',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('app_id', sa.Text(), nullable=False),
    sa.Column('execution_source', sa.Text(), nullable=False),
    sa.Column('draft_revision', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('inputs_json', sa.Text(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_by', sa.Text(), nullable=False),
    sa.Column('graph_json', sa.Text(), nullable=False),
    sa.Column('graph_sha256', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('finished_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['workflow_applications.app_id'], name=op.f('fk_workflow_runs_app_id_workflow_applications')),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_workflow_runs'))
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index('idx_workflow_runs_app_created', ['app_id', sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index('idx_workflow_runs_app_status', ['app_id', 'status', sa.literal_column('created_at DESC')], unique=False)

    op.create_table('workflow_versions',
    sa.Column('version_id', sa.Text(), nullable=False),
    sa.Column('app_id', sa.Text(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('source_draft_revision', sa.Integer(), nullable=False),
    sa.Column('graph_json', sa.Text(), nullable=False),
    sa.Column('graph_sha256', sa.Text(), nullable=False),
    sa.Column('release_notes', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('published_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['workflow_applications.app_id'], name=op.f('fk_workflow_versions_app_id_workflow_applications')),
    sa.PrimaryKeyConstraint('version_id', name=op.f('pk_workflow_versions')),
    sa.UniqueConstraint('app_id', 'source_draft_revision', name='uq_workflow_versions_app_draft_revision'),
    sa.UniqueConstraint('app_id', 'version_number', name='uq_workflow_versions_app_version')
    )
    with op.batch_alter_table('workflow_versions', schema=None) as batch_op:
        batch_op.create_index('idx_workflow_versions_app_version', ['app_id', sa.literal_column('version_number DESC')], unique=False)

    op.create_table('workflow_review_requests',
    sa.Column('review_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('node_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('reviewer', sa.Text(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.run_id'], name=op.f('fk_workflow_review_requests_run_id_workflow_runs')),
    sa.PrimaryKeyConstraint('review_id', name=op.f('pk_workflow_review_requests')),
    sa.UniqueConstraint('run_id', 'node_id', name='uq_workflow_reviews_run_node')
    )
    with op.batch_alter_table('workflow_review_requests', schema=None) as batch_op:
        batch_op.create_index('idx_workflow_reviews_run_status', ['run_id', 'status', 'created_at'], unique=False)

    op.create_table('workflow_run_events',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('node_id', sa.Text(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.run_id'], name=op.f('fk_workflow_run_events_run_id_workflow_runs')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_workflow_run_events'))
    )
    with op.batch_alter_table('workflow_run_events', schema=None) as batch_op:
        batch_op.create_index('idx_workflow_run_events_run_created', ['run_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_run_events', schema=None) as batch_op:
        batch_op.drop_index('idx_workflow_run_events_run_created')

    op.drop_table('workflow_run_events')
    with op.batch_alter_table('workflow_review_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_workflow_reviews_run_status')

    op.drop_table('workflow_review_requests')
    with op.batch_alter_table('workflow_versions', schema=None) as batch_op:
        batch_op.drop_index('idx_workflow_versions_app_version')

    op.drop_table('workflow_versions')
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index('idx_workflow_runs_app_status')
        batch_op.drop_index('idx_workflow_runs_app_created')

    op.drop_table('workflow_runs')
    op.drop_table('workflow_drafts')
    with op.batch_alter_table('workflow_audit_events', schema=None) as batch_op:
        batch_op.drop_index('idx_workflow_audit_app_created')

    op.drop_table('workflow_audit_events')
    with op.batch_alter_table('ops_graph_checkpoints', schema=None) as batch_op:
        batch_op.drop_index('idx_ops_graph_checkpoints_thread_run')
        batch_op.drop_index('idx_ops_graph_checkpoints_task_created')

    op.drop_table('ops_graph_checkpoints')
    with op.batch_alter_table('knowledge_ingestion_attempts', schema=None) as batch_op:
        batch_op.drop_index('idx_knowledge_ingestion_attempts_status')

    op.drop_table('knowledge_ingestion_attempts')
    with op.batch_alter_table('human_review_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_human_review_requests_task_created')
        batch_op.drop_index('idx_human_review_requests_status_created')

    op.drop_table('human_review_requests')
    with op.batch_alter_table('diagnosis_task_events', schema=None) as batch_op:
        batch_op.drop_index('idx_diagnosis_task_events_task_created')

    op.drop_table('diagnosis_task_events')
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.drop_index('idx_diagnoses_incident_created')

    op.drop_table('diagnoses')
    with op.batch_alter_table('workflow_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_workflow_applications_status_updated')

    op.drop_table('workflow_applications')
    with op.batch_alter_table('knowledge_ingestion_tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_knowledge_ingestion_tasks_status_created')

    op.drop_table('knowledge_ingestion_tasks')
    with op.batch_alter_table('knowledge_index_manifest', schema=None) as batch_op:
        batch_op.drop_index('idx_knowledge_manifest_namespace')

    op.drop_table('knowledge_index_manifest')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('idx_incidents_service_status_created')

    op.drop_table('incidents')
    with op.batch_alter_table('diagnosis_tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_diagnosis_tasks_thread_created')
        batch_op.drop_index('idx_diagnosis_tasks_status_updated')
        batch_op.drop_index('idx_diagnosis_tasks_resume_of')
        batch_op.drop_index('idx_diagnosis_tasks_rerun_of')

    op.drop_table('diagnosis_tasks')
    with op.batch_alter_table('alert_groups', schema=None) as batch_op:
        batch_op.drop_index('idx_alert_groups_status_last_seen')

    op.drop_table('alert_groups')
    # ### end Alembic commands ###
